### ISSUE TITLE
[Bug] Image styles not being applied properly

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/hackportal-hackutd#1]
# Overview

The index page is missing a few assets from the jumbotron's background.

![image](https://user-images.githubusercontent.com/16641570/127578623-620a5f13-4c38-46c7-b963-cf4479296035.png)

# Expected Behavior

The website should render all the images from the mockups.

# Actual Behavior

The site doesn't display the logo or any of the photos in the jumbotron.

The only error message in the console is:

```
Failed to load resource: the server responded with a status of 404 ()
```

The `styles/global.css` file is likely the culprit here.

**Comment by WillieCubed** [comment]
Updates: it doesn't work on Chrome and Microsoft Edge (likely the Chromium version).

@ThaisCampanac put more information as you get it.

**Comment by ThaisCampanac** [comment]
At the moment the only websites that displays the images are FireFox and Internet Explorer. Besides those all Chromium versions are ignoring all css code that displays the background images. I have tried targeting those websites and made the css code !important and no avail. The latest I have read online was that it was a javascript error.

**Comment by Jariel97** [comment]
Svgs, needed an edit, change xlink:href="data:img/png;base64, to xlink:href="data:image/png;base64

**Comment by ThaisCampanac** [comment]
Thank you Jariel! That fixed everything on Chrome and Microsoft Edge.
