### ISSUE TITLE
[Bug] Cookies Error 

### ISSUE THREAD

**Issue by ThaisCampanac** [acmutd/hackportal-hackutd#2]
# Overview
Within Chrome, the Issues bar is giving cookies error.
![image](https://user-images.githubusercontent.com/53068070/127716719-11735f5d-e9ee-4d66-ac5d-790f12837852.png)

# Expected Behavior
Cookies are specified across all sites through the SameSite Attribute.

# Actual Behavior 
The site is redoing the same error of
```
Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
```

**Comment by Jariel97** [comment]
This is mostly cause we are using the youtube video in the iframe, youtube wants to store its cookies whenever the iframe loads causing cross site cookies, so we either ignore the warning or have a mechanism to consent to cookies to youtube.

Tried changing the url to : youtube-nocookies, but that just reduces all to a single "Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute" issue.

Src: https://complianz.io/youtube-and-the-gdpr-how-to-embed-youtube-on-your-site/

**Comment by WillieCubed** [comment]
Closing as this has been mysteriously resolved in the past month.
