### ISSUE TITLE
[Bug] TypeForm not working on Safari

### ISSUE THREAD

**Issue by natesabrown** [acmutd/hackportal-hackutd#5]
### What did you expect to happen?

The sign-up TypeForm should work on Safari.

### What happened?

A blank page is shown when you click the "Become a Hacker" button on Safari. I have an AdBlocker, but other than that I'm pretty sure it's a bug.

<img width="1268" alt="Screen Shot 2021-09-30 at 8 55 13 PM" src="https://user-images.githubusercontent.com/45186473/135553691-6b8d1d58-3258-436e-8c23-bc2a178693c0.png">

### Scope

Registration

### What browsers are you seeing the problem on?

Safari

**Comment by natesabrown** [comment]
OK it turns out it was just because of my AdBlocker so this shouldn't be the case for everyone.

**Comment by WillieCubed** [comment]
Hey Nate, thanks for letting us know and following up once you realized the issue! If you have any other suggestions or feedback for HackPortal, you're welcome to let us know in the future!
